# Generated by Django 5.0 on 2023-12-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodexpress_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='default.png', max_length=255),
        ),
    ]
