# Generated by Django 5.0 on 2023-12-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodexpress_app', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
