# Generated by Django 5.0 on 2023-12-27 16:10

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodexpress_app', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='foodexpress_app.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
